### ISSUE TITLE
LINE Login verification screen shows provider name instead of app name

### ISSUE THREAD

**Issue by leshik** [line/line-sdk-ios-swift#10]
Not sure if it's iOS SDK issue or not, but when verifying login permissions in LINE app, the `Important` section shows the provider name in its text instead of the app name, e.g:

![img_6836](https://user-images.githubusercontent.com/443678/50076096-4ebaa600-0213-11e9-80ba-5db99a72430b.png)

In this example, `Learn21` is the app name, and `HEADSTART EDUCATION MANAGEMENT COMPANY LIMITED` is the provider. It looks weird to read about downloading a company. :)

**Comment by onevcat** [comment]
Thanks for opening this. I'll forward it to see whether it is intended or not.

**Comment by onevcat** [comment]
@LiYing2010 Could you check it?

**Comment by LiYing2010** [comment]
Mr   @ikebe  :
Thanks very much for reporting this.
Looks like this is a Server Side web page issue, we will fix it soon.

**Comment by onevcat** [comment]
@leshik Thanks for the feedback!

**Comment by LiYing2010** [comment]
> PS: It shows the unneeded spacing after the provider name and before the period, not critical but maybe you'll want to fix it so it looks nicer. :)

Yes, you are right.
Thank for your suggestion, we will work on it.
