### ISSUE TITLE
'SecCertificateCopyPublicKey' is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by xiao99xiao** [line/line-sdk-ios-swift#108]
## What did you do?

Enable the mac option for an iOS target in Xcode 11.1, that is, The Catalyst.
Build it.

## What did you expect?

Build successfully.

## What happened actually?

Got error at CryptoHelpers.swift Line#172 in LineSDKSwift target saying:
`'SecCertificateCopyPublicKey' is unavailable in Mac Catalyst`

After some investigation, seems `SecCertificateCopyPublicKey ` is marked as `deprecated` since iOS 10.2, and `SecCertificateCopyKey` is recommended in the Documentation from here https://developer.apple.com/documentation/security/1396096-seccertificatecopypublickey

Though there is actually no harm to any existing iOS projects, it would great if we could get this fixed to make the transition for any projects targeting `iosmac` more easily.

## Your environment?

LINE SDK version 5.3.0
Xcode version 11.1
macOS version 10.15

**Comment by onevcat** [comment]
See comments in #109

**Comment by onevcat** [comment]
Basic support for macCatalyst was added in #111 

We will find a good time to merge and release it in the future.

**Comment by onevcat** [comment]
macCatalyst is supported from [version 5.4.0](https://github.com/line/line-sdk-ios-swift/releases/tag/5.4.0).
