### ISSUE TITLE
About the iOS version of LineSDKObjC.framework

### ISSUE THREAD

**Issue by nrikiji** [line/line-sdk-ios-swift#13]
Please let me ask a question about the supported iOS version.

After `carthage update` we checked framework information with the following command, LineSDKObjC.framework did not include armv7. Will it be said that this is not compatible with iOS 10?

Is my procedure wrong?
```
$ xcrun lipo -info Carthage/Build/iOS/LineSDK.framework/LineSDK 
Architectures in the fat file: Carthage/Build/iOS/LineSDK.framework/LineSDK are: i386 x86_64 armv7 arm64 

$ xcrun lipo -info Carthage/Build/iOS/LineSDKObjC.framework/LineSDKObjC 
Architectures in the fat file: Carthage/Build/iOS/LineSDKObjC.framework/LineSDKObjC are: x86_64 arm64 
```

**Comment by onevcat** [comment]
I can confirm it. It seems to be a mistake of build setting config. A fix would be applied soon.

**Comment by onevcat** [comment]
@nrikiji Can you try this branch `fix/build-setting` for now? If everything goes fine, we could release a patch for it. Thanks!

**Comment by nrikiji** [comment]
Thank you. confirmed.
```
$ xcrun lipo -info Carthage/Build/iOS/LineSDK.framework/LineSDK
Architectures in the fat file: Carthage/Build/iOS/LineSDK.framework/LineSDK are: i386 x86_64 armv7 arm64 
$ xcrun lipo -info Carthage/Build/iOS/LineSDKObjC.framework/LineSDKObjC
Architectures in the fat file: Carthage/Build/iOS/LineSDKObjC.framework/LineSDKObjC are: i386 x86_64 armv7 arm64 
```

**Comment by onevcat** [comment]
[5.0.3](https://github.com/line/line-sdk-ios-swift/releases/tag/5.0.3) was released for this issue.
