### ISSUE TITLE
Can't login with Sample Project

### ISSUE THREAD

**Issue by RyoZaizen2** [line/line-sdk-ios-swift#149]
Recently, there was an inquiry from the user of our service, and I noticed error on LINE login.
I tried the sample, but has same error.

Error:
On Tap Login Button on sample, Line app show error popup.(image)

Environment:
Xcode11.3.1 MacOS Catalina10.15.4 iOS13.4 LINE App 10.3.0

I also create thread on developers community(japanese).
https://www.line-community.me/question/5e87c28d851f7402cd9668a4

![iOS の画像](https://user-images.githubusercontent.com/54798135/78520168-9f875100-7800-11ea-8dbb-d6b2f4ae1124.png)

**Comment by onevcat** [comment]
I tried the sample app with our demo channel and everything goes fine. 

This issue happens in the LINE app and I guess maybe @LiYing2010 can help to check what is happening.

**Comment by onevcat** [comment]
@RyoZaizen2 Can I know your channel ID so we can check your log to know what is happening.

Basically, the `redirect_uri` is related to some unmatched setting of the return URL. Before we can investigate, would you mind to also check you have set the correct "iOS bundle ID" value in the developer console for your channel? Thanks!

**Comment by LiYing2010** [comment]
>Before we can investigate, would you mind to also check you have set the correct "iOS bundle ID" value in the developer console for your channel? Thanks!

please refer this doc, about how to setup your channel: 
https://developers.line.biz/en/docs/ios-sdk/swift/setting-up-project/#linking-app-to-channel

**Comment by RyoZaizen2** [comment]
@onevcat @LiYing2010 thank you for response.

Channel ID:
1595955568

In my device, sample channel id is not working well. it has same error.

![ 2020-04-06 12 57 59](https://user-images.githubusercontent.com/54798135/78521859-4d492e80-7806-11ea-9a44-09a09bb75ff1.jpg)

![ 2020-04-06 12 57 52](https://user-images.githubusercontent.com/54798135/78521858-4b7f6b00-7806-11ea-9a01-945da2d83307.jpg)

**Comment by RyoZaizen2** [comment]
On error in Line App,  I redirected to safari, Line login page with error.
This is the url of page.
https://access.line.me/oauth2/v2.1/login?fromDomain=access-auto.line.me&line_auto_login_error=universal_link_error&loginChannelId=1620019587&returnUri=%2Foauth2%2Fv2.1%2Fauthorize%2Fconsent%3Fclient_id%3D1620019587%26response_type%3Dcode%26state%3Dl-f3SmQVP_zTHtryC8Kes2PqNGyJ8_r-mmIkw6WKq5o%26redirect_uri%3Dline3rdp.jp.budonoki.lynomilivestream%253A%252F%252Fauthorize%252F%26scope%3Dopenid%2520friends%2520profile%2520groups%2520onetime.share%26nonce%3DwscXnpgAvIXw6LKssQ3o009EYC-cSulHtB4KYumU5lI%26sdk_ver%3D5.5.1%26code_challenge%3DsW3DwCrnpkNXmQyLcxE88TCP_wh_NuocmIgsN4I2OvQ%26code_challenge_method%3DS256#/

**Comment by onevcat** [comment]
It seems that you are using “ jp.budonoki.lynomilivestream” as your bundle ID in the app, but you set it as “ jp.budonoki.lynomi” in the Developer Console, which is not matching the app. If you are sure that “ jp.budonoki.lynomilivestream” is your correct bundle ID, you can try to add it to the Developer Console too to make the verification pass.

**Comment by RyoZaizen2** [comment]
@onevcat oh, I missed it! thank you! I will try.

**Comment by RyoZaizen2** [comment]
After fix, line login successed. thank you for your great advice!And I 
I will close this issue.
