### ISSUE TITLE
在OC中使用出现的问题

### ISSUE THREAD

**Issue by yangdehui** [line/line-sdk-ios-swift#152]
在OC中使用line登录SDK， 登录成功回调不走

**Comment by onevcat** [comment]
The Objective-C version of SDK is using as a part of our Unity SDK and also quite a few other developers are using it without a problem. We also tried it again and everything is working as expected.

A typical error is forgetting of implementation of `openURL` in either `AppDelegate` or `SceneDelegate`. If you are still not calling `LoginManager.application:open:options` in your app delegate or scene delegate, please refer to [this doc to add them](https://developers.line.biz/zh-hant/docs/ios-sdk/swift/integrate-line-login/#setting-up-the-linesdk-framework-and-your-channel-id) (They are using Swift, and you may need to convert these code to ObjC if necessary).

If you still cannot get it to work, can you share us some code snippet to describe what did you do? Or even better, prepare a sample project, so we can take a deeper look into it.

Thanks!

**Comment by yangdehui** [comment]
We've replaced the objective-c version with the Swift version
Thanks!

**Comment by onevcat** [comment]
Thanks for the feedback!
