### ISSUE TITLE
Cannot login my app by line account in iOS 13

### ISSUE THREAD

**Issue by czars** [line/line-sdk-ios-swift#164]
## What did you do?

Login my app with Line in iPad iOS 13 version, it will lead to a web page.
After entering my user email/password, it shows 500 internal server error.

## What did you expect?

I can log in with Line account in iOS 14 with the same version of line app and my own app

## Your environment?

iOS 13.2.3 with Line SDK 5.6.2 

## Screenshot

![IMG_0009](https://user-images.githubusercontent.com/1787422/102957185-cd3e3280-4514-11eb-901d-ffde435ef698.PNG)

**Comment by onevcat** [comment]
@LiYing2010 Not sure what happens but it seems like the server is giving a 500 in this case. Can you help with it?

@czars Can you please provide some basic information about this issue? At least we need the Channel ID you are using. And this issue happens at 11:44(UTC+8) today, is that correct?

**Comment by LiYing2010** [comment]
@czars  :

thank you very much for reporting this issue.

for further investigation, could you please share us more information, like
- your channel id
- your LINE Account (email)
- timestamp when this issue occurred


Thanks very much

**Comment by czars** [comment]
@LiYing2010 ok, let me collect the info for you. Should I email you for further investigation?

**Comment by LiYing2010** [comment]
@czars 
please just left comment here in this issue if these info are not confidential

**Comment by czars** [comment]
ChannelID : `1654204404`
Email : czarsterchou@gmail.com
timestamp : `12/24/2020 @ 2:32am (UTC)` or `1608777160`

**Comment by LiYing2010** [comment]
(1) looks like the iOS bundle ID setting for your channel `1654204404` is now `com.iqiyi.i18n` only,

(2) but your login redirect url is `line3rdp.com.iqiyi.i18n.enterprise://authorize/`,
which using bundle ID `com.iqiyi.i18n.enterprise`

currently LINE Login request that these 2 setting fully equals.
(@onevcat san: correct me if I am wrong)

so please try any of the following:
(A) change (or add a new) iOS bundle ID for your channel: `com.iqiyi.i18n.enterprise`
or
(B) change your iOS App bundle ID to `com.iqiyi.i18n`

and please let us know if it works.

thanks and regards

**Comment by czars** [comment]
I see. I'll let our QA know this limitation about our enterprise version app.
It should be quickly resolved if we can access our own line developer dashboard. haha.
Thank you for your help.

**Comment by LiYing2010** [comment]
@czars 

BTW
for this kind of bundle ID mismatch, LINE Login Server should respond a `400 Bad Request` error with error message `Invalid redirect_uri value. Check if it is registered in a LINE developers site.`
but it respond `500 Internal Error` now due to some implementation mistake.

We think this is a minor bug and we will fix it soon.

**Comment by LiYing2010** [comment]
JFYI

> We think this is a minor bug and we will fix it soon.

It was fixed
