### ISSUE TITLE
Cannot find 'LoginManager' in scope

### ISSUE THREAD

**Issue by abinhho** [line/line-sdk-ios-swift#176]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?
![Screenshot 2022-06-03 at 14 16 52](https://user-images.githubusercontent.com/9253378/171806593-fd23ccb0-acee-4b17-a3ca-de3b62fdef7b.png)

![Screenshot 2022-06-03 at 14 16 47](https://user-images.githubusercontent.com/9253378/171806557-4ad340e8-fdea-4ccc-9b4a-f00e24246b6c.png)

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

Displaying error `Cannot find 'LoginManager' in scope`
> Please describe what happened actually.

## Your environment?

- XCode 13.3
- Swift
> Some information of the environment in which the issue happened. LINE SDK version, Xcode version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
It is more likely a linking issue than a problem inside the package. Can you please attach or send us a minial sample project, so I could take a detail look into that to see what is going on.

**Comment by abinhho** [comment]
@onevcat Thank you for your answer. I firegure out I need to change `pod 'LineSDK'` to `pod 'LineSDKSwift'`

But goto this page, when I clicked the button `OK`, an error message displayed. What should I do?

```
Safari can not open the page because the address is invalid
```

![Screenshot 2022-06-03 at 15 07 15](https://user-images.githubusercontent.com/9253378/171814762-22938242-8a2a-4fc9-a6ec-fec7f4fc49ac.png)


Brgs!!!

**Comment by onevcat** [comment]
I guess that basically means you are not setting the callback URL scheme correctly in your Info.plist. Please make sure you are following [the guide here](https://developers.line.biz/en/docs/ios-sdk/swift/setting-up-project/#config-infoplist-file) to set the correct value (matching the setting Developer Console for your channel) to `CFBundleURLSchemes` key in your app, so LINE SDK can go back to your app by that scheme.

**Comment by abinhho** [comment]
@onevcat So sorry for taking your time. I just set it as the guideline and now the button "OK" works now. But callback has something wrong. I click OK but the callback error is `userCancelled`

This is my code

```
struct LineLoginButton: UIViewRepresentable {
    class Coordinator: NSObject, LoginButtonDelegate {
        var parent: LineLoginButton
        
        init(_ parent: LineLoginButton) {
            self.parent = parent
        }
        
        func loginButton(_ button: LoginButton, didSucceedLogin loginResult: LoginResult) {
            LOGGING.debug("LINE didSucceedLogin token", loginResult.accessToken.value)
            LOGGING.debug("LINE loginResult", loginResult)
        }
        
        func loginButton(_ button: LoginButton, didFailLogin error: LineSDKError) {
            LOGGING.error("LINE login error", error)
        }
        
        func loginButtonDidStartLogin(_ button: LoginButton) {
            LOGGING.error("LINE login started")
        }
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    func makeUIView(context: Context) -> UIView {
        let view = UIView()
        return view
    }
    
    func updateUIView(_ view: UIView, context: Context) {
        let loginButton = LoginButton()
        loginButton.delegate = context.coordinator
        
        loginButton.permissions = [.profile]
        loginButton.presentingViewController = nil
        
        view.addSubview(loginButton)
        
        loginButton.translatesAutoresizingMaskIntoConstraints = false
        loginButton.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        loginButton.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
    }
}

```

```
==== ERROR LINE login started 
==== ERROR LINE login error authorizeFailed(reason: LineSDK.LineSDKError.AuthorizeErrorReason.userCancelled)
```

**Comment by abinhho** [comment]
@onevcat Please forget the above, After I added SceneDelegate, it works now. I did not add this because my app does not have `SceneDelegate` class, so I have to add it.
```
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        _ = LoginManager.shared.application(.shared, open: URLContexts.first?.url)
}
```

**Comment by onevcat** [comment]
Thanks for the feedback. If your app is a scene based one, you need to add that method to handle result and give LINE SDK a chance to process the auth response.

Glad to hear it is working for you!
