### ISSUE TITLE
ios版本的怎么分享图片呢？

### ISSUE THREAD

**Issue by agni** [line/line-sdk-ios-swift#183]
安卓使用安卓自己的方式分享图片是可以 的，但ios怎么解决呢。代码如下：
//图片分享
    @objc static func shareWithLineWithUrlStr(urlStr: String) {
         //Share image
        let pasteboard = UIPasteboard.general
        pasteboard.setData(UIImage(named: urlStr)!.jpegData(compressionQuality: 1.0)!, forPasteboardType: "public.jpeg")
        let contentType = "image"
        let urlString = "line:msg/\(contentType)/\(pasteboard.name)" // Get image from pasteboard, you can also use this method to share text
        let url = URL(string: urlString)!
        print(url)
        
        if UIApplication.shared.canOpenURL(url) {
            UIApplication.shared.open(url, options: [:], completionHandler: nil)
        } else {
            print("分享失败")
        }
    }
app崩溃了，求大神解决

**Comment by onevcat** [comment]
For iOS, I recommend using the system provided `UIActivityViewController` and setting your image as the sharing item to perform the share action. The `line:` scheme is already deprecated and not encouraged to use anymore. 

[Ref: LINE URL Schemes](https://developers.line.biz/en/docs/line-login/using-line-url-scheme/)
