### ISSUE TITLE
跳转line app 授权失败，使用web授权成功

### ISSUE THREAD

**Issue by zhongdom** [line/line-sdk-ios-swift#184]
SDK 版本：5.8.2
line app版本：13.6.0

安装line app后，唤起line app授权，返回错误：authorizeFailed(reason: LineSDK.LineSDKError.AuthorizeErrorReason.userCancelled)

不安装line app，使用web授权没问题

**Comment by onevcat** [comment]
Hi,

Thanks for the report.

I tried the demo app with the same SDK version/LINE app version, but unfortunately cannot reproduce this issue. (The demo app is also in this same repo, and you can also have try with that too to see if it works).

Does it always happen every time on all devices? Or is it a rare case? If the latter, I would guess it is again something with #159 :[

**Comment by zhongdom** [comment]
@onevcat Thanks for you reply. It's our  problem.

Line app back to our app will triger the method：
`application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable restorableObjects))restorationHandler`,

universal  link url was processed by other SDK, so line SDK can't get the url.

**Comment by onevcat** [comment]
Thanks for the feedback. Nice to hear that you found it!

Good luck and may your code always compile on the first try :] !
