### ISSUE TITLE
how to get "id_token" in lineSDKObjC ?

### ISSUE THREAD

**Issue by shuaku110dai** [line/line-sdk-ios-swift#185]
how to get "id_token" in lineSDKObjC?

请问一下，哥，如何在lineSDKObjC的SDK里面获取LineSDKAccessToken的json字符串中id_token字段(当权限允许openID)，我看LineSDKAccessToken的结构里面没有哇，谢谢大哥。

**Comment by onevcat** [comment]
I believe there is an `IDToken` property, by which you can access the fields in the ID Token (which in turn is a JWT under the hood):

```objc
LineSDKAccessToken *token = store.currentToken;
LineSDKJWT *idToken = token.IDToken;
NSLog(@"User Name: %@", idToken.payload.name);
```

**Comment by shuaku110dai** [comment]
1 你好，哥，通过你说的代码，就是下面
`LineSDKAccessToken *token = store.currentToken; 
 LineSDKJWT *idToken = token.IDToken;
 NSLog(@"User Name: %@", idToken.payload.name);`

这个结构暴露的好像是IDToken解析出来的一系列属性。

2 但是我这边的需求是想要的是IDToken的原始字符串，需求如下图所示：
![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/80e290a1-5b8f-435a-95ba-e7fbbb80d942)

3 我这边看您5.2.9最新的源码里面大概可能是下图这样一个属性里面的值：

![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/73821912-6058-4a48-872c-522a0abf696d)
![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/2eaacfd2-8b8f-4199-8953-682dcb7f870a)
或者
![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/851c4e69-3ecc-4458-a2d8-9a0969543d5e)

4 总结：我该如何获取第2点截图里面的那个id_token字段呐，期待哥的回复

**Comment by shuaku110dai** [comment]
> I believe there is an `IDToken` property, by which you can access the fields in the ID Token (which in turn is a JWT under the hood):
> 
> ```objc
> LineSDKAccessToken *token = store.currentToken;
> LineSDKJWT *idToken = token.IDToken;
> NSLog(@"User Name: %@", idToken.payload.name);
> ```

1 你好，哥，通过你说的代码，就是下面

     LineSDKAccessToken *token = store.currentToken; 
     LineSDKJWT *idToken = token.IDToken;
     NSLog(@"User Name: %@", idToken.payload.name);

这个结构暴露的好像是IDToken解析出来的一系列属性。

2 但是我这边的需求是想要的是IDToken的原始字符串，需求如下图所示：
![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/80e290a1-5b8f-435a-95ba-e7fbbb80d942)

3 我这边看您5.9.0最新的源码里面大概可能是下图这样一个属性里面的值：

![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/73821912-6058-4a48-872c-522a0abf696d)
![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/2eaacfd2-8b8f-4199-8953-682dcb7f870a)
或者
![image](https://github.com/line/line-sdk-ios-swift/assets/21141716/851c4e69-3ecc-4458-a2d8-9a0969543d5e)

4 总结：我该如何获取第2点截图里面的那个id_token字段呐，期待哥的回复

**Comment by shuaku110dai** [comment]
明白了，谢谢哥，我等哥更新，然后我这边在更新版本，哥yyds!!!。

**Comment by onevcat** [comment]
[Version 5.9.1](https://github.com/line/line-sdk-ios-swift/releases/tag/5.9.1) was released and the related property is now added. Please try to upgrade to it to get that raw string.

Thanks for reporting it and the kind feedback.
