### ISSUE TITLE
【Urgent】https://d.line-scdn.net CDN Server is down,LineSDK will  pod install fail

### ISSUE THREAD

**Issue by qinqinHe-iOS** [line/line-sdk-ios-swift#201]
https://github.com/CocoaPods/Specs/blob/master/Specs/c/a/5/LineSDK/5.0.2/LineSDK.podspec.json

When pod install, it will fail because it can't download LineSDK.CDN service exception, please deal with it urgently.
https://d.line-scdn.net/r/devcenter/ios/LineSDK_ios_5.0.2.zip

**Comment by onevcat** [comment]
Hi,

The ObjC SDK you mentioned has been deprecated from 2018, and recently has been completely removed from 10/26. Please consider to migrate to the latest LINE SDK Swift versions.

Ref: https://developers.line.biz/en/news/2023/10/26/finish-providing-line-sdk-for-ios-objective-c/
