### ISSUE TITLE
Login with UniversalLinkFlow auto direct Safari browser

### ISSUE THREAD

**Issue by TrongTran-98** [line/line-sdk-ios-swift#202]
Hello, I'm applying Line login flow, but when I tried to call Login with UniversalLinkFlow when the Line app was installed before without login, when the Line App opened then auto-directed to the Safari browser.
- So In this case how to configure to Line app to keep that session without directing it to the browser?
- I have referred to another app like TikTok when logging Line no login yet, but the Line app still keeps that session.
- I also tried the example on Line SDK, whose behavior is still directed to the browser.

**Comment by onevcat** [comment]
Maybe duplicated to https://github.com/line/flutter_line_sdk/issues/90

We are discussing the behavior internally. However, navigating to the web browser and allow users to continue the login process there seems to be a "not bad" solution for now. We will see if there is any way to provide a better UX, but now I cannot give any promise about it.

**Comment by TrongTran-98** [comment]
But I still have a question: why does the TikTok apply Line login still keep the Line app session instead of directing Webpage?  Do have another version, solutions, etc,.. or do they do it on their own?

**Comment by TrongTran-98** [comment]
Can anyone help me answer my questions?

**Comment by onevcat** [comment]
> But I still have a question: why does the TikTok apply Line login still keep the Line app session instead of directing Webpage? Do have another version, solutions, etc,.. or do they do it on their own?

To my understanding, we do not provide any 'distinct version'. The behavior of LINE on iOS and Android platforms differs: on iOS, a webpage login is utilized, whereas on Android, the user is required to login within the LINE app itself. However, on Android, the user is not automatically redirected back to your application even after logging in. It necessitates initiating another login process from your application.

Could you clarify if you are experimenting on different platforms?
