### ISSUE TITLE
PrivacyInfo.xcprivacy questions on ios 12

### ISSUE THREAD

**Issue by bforrose** [line/line-sdk-ios-swift#203]
안녕하세요. Line SDK 사용 중에 문의 사항이 있습니다.

Line SDK 5.7.0 버전을 사용하고 있으며 5.11.0 버전부터 Apple의 Privacy Manifest 대응이 되는 것으로 확인하였습니다.
우리의 환경은 최소 iOS 12부터 지원하기 때문에 iOS 13부터 지원하는 5.11.0을 사용할 수 없습니다.
그래서 5.7.0을 그대로 사용하기를 희망합니다.

질문.
1. 5.11.0의 Privacy Manifest 파일을 5.7.0에서 사용해도 문제가 없을지 궁금합니다. 5.7.0의 "LineSDKUI.bundle/PrivacyInfo.xcprivacy" 위치에 포함하려고 합니다.
2. 5.7.0과 5.11.0의 버전 차이로 Privacy Manifest 내용에 변경이 필요한 부분이 있을지 궁금합니다.

감사합니다.

=====

Hello. I have a question while using the Line SDK.

We are using the Line SDK version 5.7.0, and we have confirmed that Apple's Privacy Manifest correspondence from version 5.11.0.
Since our environment supports iOS 12 at least, 5.11.0 that supports iOS 13 is not available.
So I hope to use 5.7.0 as it is.

Question.
1. I'm wondering if the Privacy Manifest file in 5.11.0 is okay with using it in 5.7.0. I'm trying to include it in the "LineSDKUI.bundle/PrivacyInfo.xcprivacy" location in 5.7.0.
2. I wonder if there is anything that needs to be changed in the Privacy Manifest content due to the difference in versions between 5.7.0 and 5.11.0.

Thank you.

**Comment by onevcat** [comment]
Hi,

Although I did not try myself, but I believe it should work by simply copying the `PrivacyInfo.xcprivacy` from 5.11.0 to the bundle of 5.7.0. Xcode does not care the source of the privacy file, but if it is there and copied to your final archive, it should be able to generate a privacy report based on that.

There is no change of related permissions and privacy policy between these two versions!

**Comment by onevcat** [comment]
I am closing this ticket since it involves a legacy version. In the latest version of LINE SDK for Swift, the privacy manifest is already supported and does not require this additional work.
