### ISSUE TITLE
无法使用cocoapods加载资源

### ISSUE THREAD

**Issue by xiepaul888** [line/line-sdk-ios-swift#205]
```
![1](https://github.com/line/line-sdk-ios-swift/assets/7138771/1fd8c81d-ae82-4648-ad59-b5a5529c10c4)

```

**Comment by onevcat** [comment]
This seems to be the ObjC SDK, which was deprecated for more than 5 years and discontinued from Oct 2023.

We do not provide it anymore and please consider to upgrade the LINE SDK for iOS Swift (this repo) instead.

Ref: https://developers.line.biz/en/news/2023/10/26/finish-providing-line-sdk-for-ios-objective-c/

**Comment by xiepaul888** [comment]
> This seems to be the ObjC SDK, which was deprecated for more than 5 years and discontinued from Oct 2023.
> 
> We do not provide it anymore and please consider to migrate to the LINE SDK for iOS Swift (this repo) instead.
> 
> Ref: https://developers.line.biz/en/news/2023/10/26/finish-providing-line-sdk-for-ios-objective-c/

We haven't scheduled any updates recently. Can the previous SDK still be used?
