### ISSUE TITLE
Privacy Manifest Scanner Report

### ISSUE THREAD

**Issue by Wei18** [line/line-sdk-ios-swift#208]
## Is it a security issue? 

N

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do? 

Run a code scanner `$ mint run techinpark/ios_privacy_manifest_scanner`
|File Path	| Used API	| Line Content |
| - | - | - |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/Networking/API/API+Auth.swift:95	| UserDefaults	| UserDefaultsValue.clear() |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/Networking/API/API+Auth.swift:153	| UserDefaults	| UserDefaultsValue.clear() |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/Utils/UserDefaultsValue.swift:2	| UserDefaults	| //  UserDefaultsValue.swift |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/Utils/UserDefaultsValue.swift:22	| UserDefaults	| enum UserDefaultsValue { |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/Utils/UserDefaultsValue.swift:24	| UserDefaults	| private static var defaults = UserDefaults.standard |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/LineSDKUI/OpenChatUI/Public/OpenChatCreatingController.swift:161	| UserDefaults	| if let cachedName = UserDefaultsValue.cachedOpenChatUserProfileName { |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/LineSDKUI/OpenChatUI/Public/OpenChatCreatingController.swift:176	| UserDefaults	| UserDefaultsValue.cachedOpenChatUserProfileName = room.creatorDisplayName |
| /SourcePackages/checkouts/line-sdk-ios-swift/LineSDK/LineSDK/Login/LoginManager.swift:140	| UserDefaults	| UserDefaultsValue.clear() |

> Please describe what you did before you encounter the issue.

## What did you expect? 

Provide a privacy manifest as Apple required

> Please describe what you did expect to happen.

## What happened actually?
If you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file, Apple sends you an email reminding you to add the reason to the app’s privacy manifest. Starting May 1, 2024, apps that don’t describe their use of required reason API in their privacy manifest file aren’t accepted by App Store Connect.
ref https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

> Please describe what happened actually.

## Your environment?

LINE SDK 5.10.1

> Some information of the environment in which the issue happened. LINE SDK version, Xcode version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
A manifest was already provided inside the project bundle here: https://github.com/line/line-sdk-ios-swift/blob/master/LineSDK/LineSDK/Resource.bundle/PrivacyInfo.xcprivacy

and from version 5.11.0 (https://github.com/line/line-sdk-ios-swift/releases/tag/5.11.0)

**Comment by Wei18** [comment]
Thanks.

**Comment by onevcat** [comment]
@Wei18 

However, as I know now, Apple is not checking or reading any privacy manifest provided by the 3rd party SDKs now. It only helps you to generate the privacy label, but without merging or helping you to create the API usage reasons. So even it is described in a 3rd party SDK (like LINE SDK for Swift here), you still need to manually add it to your own privacy manifest of your app level. Otherwise, you may still receive warnings from Apple.

No one knows if the situation would change soon or not, and there is no promise from Apple too as I know. Please keep that in mind!
