### ISSUE TITLE
Urgent: Line SDK Contains Bitcode, Causing App Store Rejection

### ISSUE THREAD

**Issue by sylvia-tencent-wmt** [line/line-sdk-ios-swift#209]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

Integrated LineSDK version 5.11.0 into our app.

## What did you expect?

Bitcode was deprecated in Xcode 14. Expect to provide framework with Bitcode disabled.

## What happened actually?

I am writing to report an issue with the Line SDK that has caused our app to be rejected during the App Store review process. The rejection notice specifically mentions that our app contains bitcode, which we have traced back to the Line SDK.

## Your environment?

Line SDK version: 5.11.0
LineObjC SDK version: 5.11.0
Xcode version: 15.2

<img width="633" alt="Screenshot 2024-05-21 at 10 35 42 AM" src="https://github.com/line/line-sdk-ios-swift/assets/150782251/ab01e797-629b-4088-8c2a-44e9b3849413">

**Comment by onevcat** [comment]
Hi,

Thanks for contacting. However, LINE SDK does not contain any setting of bit code. May I know in which way you are integrating LINE SDK to your project? Can it be an issue of your package manager or build settings?

**Comment by sylvia-tencent-wmt** [comment]
Hi, thank you for your prompt response. I integrated the LINE SDK by adding it into my project as framework

**Comment by onevcat** [comment]
@sylvia-tencent-wmt 
Ummm.. I guess I know the reason. Please stay tunned!

**Comment by onevcat** [comment]
@sylvia-tencent-wmt This should be solved in 5.11.1. Can you try binaries from that new version again? Thanks!

https://github.com/line/line-sdk-ios-swift/releases/tag/5.11.1
