### ISSUE TITLE
运行 官方demo，登录成功，获取好友权限失败

### ISSUE THREAD

**Issue by Rookie7118** [line/line-sdk-ios-swift#212]
在接入line sdk的时候，按照官方文档，在后台注册了 login channel，然后在xcode项目修改了对应的参数
登录成功，但是在登录之前中选择权限的时候，即使选择了 profile +其他的权限，登录成功之后，返回的token中仍然只有profile的权限。
在调用 get friends 接口的时候 报错  403.
channel id  2006149433
请问这个是什么原因，应该怎么解决？谢谢
![391724586053_ pic](https://github.com/user-attachments/assets/36ab834c-179e-490e-917a-8e3162cce3c6)
![401724586054_ pic](https://github.com/user-attachments/assets/5392a644-43b5-46ab-882a-018bd27de071)
![411724586055_ pic](https://github.com/user-attachments/assets/bc5df062-3f8f-4575-8c72-38f3317494d8)
![WechatIMG42](https://github.com/user-attachments/assets/ed56c304-f6bb-438c-b3a2-c156df446b88)

在管理后台注册一个  message  api channel  ，使用  message  channel的  id进行登录，报错如下
![image](https://github.com/user-attachments/assets/060aefe4-3c9a-4f3c-ad1b-498c004ad89a)

**Comment by onevcat** [comment]
Not all APIs defined is available for public usage, for example, the get friends APIs requires a partner plan with special permission and review before usage (I am not sure about the detail but you can try to contact to the business support team [through here](https://www.lycbiz.com/jp/)). Please check the public APIs from the documentation here to make sure of using opened ones: https://developers.line.biz/en/reference/ios-sdk-swift/

You can also check the words "LINE internal use only." to know the public status of an API.
