### ISSUE TITLE
Convert LineSDKSwift to use resource_bundles for cocoapods

### ISSUE THREAD

**Issue by cltnschlosser** [line/line-sdk-ios-swift#76]
## What did you do?

`sp.resources     = ["LineSDK/LineSDK/Assets.xcassets", "LineSDK/LineSDK/Resource.bundle"]` triggers https://github.com/CocoaPods/CocoaPods/issues/8431 which can cause apps to pull in excessive amounts of resources.

Please update to `resource_bundles`, which has numerous benefits aside from working around this issue.

**Comment by onevcat** [comment]
@cltnschlosser Thanks for reporting this. I didn't know that issue and would have some investigation on it.

And yes, you are right, we should use `resource_bundles` instead and I'd also check whether it is compatible with our project.

Thank you.

**Comment by onevcat** [comment]
Merged and will be released in the next minor version. @cltnschlosser Thank you for the suggestion!
