### ISSUE TITLE
Can I use this SDK on iOS8.0?

### ISSUE THREAD

**Issue by KKFantasy** [line/line-sdk-ios-swift#8]
If I want to use the line login before iOS 10.0, do I have to use the previous SDK?

Look forward to your suggestions, thx.

**Comment by onevcat** [comment]
Hi,

LINE SDK Swift 5.0 only supports from iOS 10.0. It is some security consideration, as well as to match the deploy target of LINE app.

If you need to support earlier iOS versions, I am afraid you need to use previous SDK versions. Please check the version 4.1 on [this page](https://developers.line.biz/en/docs/ios-sdk/deprecated/objective-c-v41/overview/).
