### ISSUE TITLE
Get a wrong SDK version when build as a static framework

### ISSUE THREAD

**Issue by congncif** [line/line-sdk-ios-swift#93]
We don’t have Info.plist in a static library so SDKVersion will return short version of main bundle.
Similar issue maybe occur with Login button resources in Assets.

**Comment by onevcat** [comment]
Hi,

Thanks for opening it.

We do not officially provide support of building LineSDK for Swift as a static library yet. Please follow the [integrating guide](https://developers.line.biz/en/docs/ios-sdk/swift/setting-up-project/) to use a dependency manager to install it.

Or if you have strong demand for building it as a static library, you may fork this repo and handle the resource loading yourself.
