### ISSUE TITLE
can't login connect with UIScene openURLContexts [BETA]

### ISSUE THREAD

**Issue by Coriolan-Bataille** [line/line-sdk-ios-swift#98]
## What did you do? / What did you expect?

To confirm login, LineSDK is using: 
`application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool`

Can't resumeOpenURL(..) since open url is not called anymore, instead the SDK should be compatible with:
`scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>)`

## What happened actually?

Login can't be confirmed.

## Your environment?

LINE SDK: 5.2.4
XCode: 11.0 beta 5 (11M382q)
iOS: 13.0 (17A5572a)

## Trying To Work Around

```swift
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
print(URLContexts.debugDescription)
        if let url = URLContexts.first?.url {
            _ = LoginManager.shared.application(UIApplication.shared, open: url)
        }
    }
```

## Console
`Set([<UIOpenURLContext: 0x280866680; URL: line3rdp.com.XXXXXXX.XXX://authorize/?code=XXXXXXXXXXXXXXXXXXXX&state=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX; options: <UISceneOpenURLOptions: 0x2806dc990; sourceApp: (null); annotation: (null); openInPlace: NO>>])
authorizeFailed(reason: LineSDK.LineSDKError.AuthorizeErrorReason.invalidSourceApplication)`

Best Regards,
Coriolan Bataille

**Comment by onevcat** [comment]
@Coriolan-Bataille Thanks for opening this.

Currently, we have not added support for scene delegate yet. We will work on it in the next version and also upgrade our documentation for it.

Before that, your workaround should work without a problem. We recently released 5.2.4 in which the `.invalidSourceApplication` will never be thrown. So I suggest you check whether your LINE SDK is the latest, and if not, please try to upgrade it then have a try!

Best regards.

**Comment by Coriolan-Bataille** [comment]
Thanks for your answer,

have a good day,
best regards,
Coriolan Bataille

**Comment by onevcat** [comment]
I think we'd better reopen it until we can update the documentation for this topic.

**Comment by sky1987a** [comment]
Did it solved?
I login and always return userCancelled on ios13

**Comment by onevcat** [comment]
@sky1987a As the [original post](https://github.com/line/line-sdk-ios-swift/issues/98#issue-485736327) said, you can just implement the open URL method in your scene delegate and pass the first URL (if exists) to `LoginManager` now to make everything works.

```swift
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    if let url = URLContexts.first?.url {
        _ = LoginManager.shared.application(UIApplication.shared, open: url)
    }
}
```

There are no any updates needed in the code of LINE SDK. We just reopen it for tracking a documentation update in the future.

**Comment by sky1987a** [comment]
I solved it!
Thanks for your answer,

**Comment by onevcat** [comment]
We've updated our documentation for this topic. Please check [the "Handle app opening" section](https://developers.line.biz/zh-hant/docs/ios-sdk/swift/integrate-line-login/#spy-setting-up-the-linesdk-framework-and-your-channel-id) to know how to deal with scene delegate.

Besides of it, if you setup the universal link to navigate back to your app, you may also want to check [how to handle it](https://developers.line.biz/zh-hant/docs/ios-sdk/swift/setting-up-project/#spy-universal-link-support) in the `scene(_ scene:continue:)` delegate method.
